@startuml
class test_domain.demo.Bike {
  brake()
  cycle()
  light_on()
  speed: None
  owner: None
  style: None
}
class test_domain.demo.Car {
  start()
  stop()
  fuel: None
  speed: None
  wheel_list: None
}
class test_domain.demo.Driver {
}
class test_domain.demo.License {
}
class test_domain.demo.Person {
}
class test_domain.demo.UmlDecorator {
  _create_classes_file()
  _create_relations_file()
  create_uml_file()
  relations: None
}
class test_domain.demo.Wheel {
}
@enduml
